// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVxCu_GCfxEdpwj34ytXIODN5Rxy0yVzM',
    appId: '1:712459874838:web:96ebf71a756f59ddbf3b37',
    messagingSenderId: '712459874838',
    projectId: 'locker-management-system-48e69',
    authDomain: 'locker-management-system-48e69.firebaseapp.com',
    storageBucket: 'locker-management-system-48e69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJHFizPPa36_C-fIy16aD39OrQDI11bis',
    appId: '1:712459874838:android:c998a6a9076137e9bf3b37',
    messagingSenderId: '712459874838',
    projectId: 'locker-management-system-48e69',
    storageBucket: 'locker-management-system-48e69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY4YMht9q19OyZl01s0479ljoeIgCUofM',
    appId: '1:712459874838:ios:d2bb0975a2784f6bbf3b37',
    messagingSenderId: '712459874838',
    projectId: 'locker-management-system-48e69',
    storageBucket: 'locker-management-system-48e69.firebasestorage.app',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY4YMht9q19OyZl01s0479ljoeIgCUofM',
    appId: '1:712459874838:ios:d2bb0975a2784f6bbf3b37',
    messagingSenderId: '712459874838',
    projectId: 'locker-management-system-48e69',
    storageBucket: 'locker-management-system-48e69.firebasestorage.app',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVxCu_GCfxEdpwj34ytXIODN5Rxy0yVzM',
    appId: '1:712459874838:web:c910cad3843192e9bf3b37',
    messagingSenderId: '712459874838',
    projectId: 'locker-management-system-48e69',
    authDomain: 'locker-management-system-48e69.firebaseapp.com',
    storageBucket: 'locker-management-system-48e69.firebasestorage.app',
  );
}
